{
  "formatVersion": "1.1",
  "component": {
    "group": "com.che300.sdk",
    "module": "hf-yjj-sdk",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "yiar47lgc5c75gq4eme7g6ugsa"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hf-yjj-sdk-1.0.0-SNAPSHOT.aar",
          "url": "hf-yjj-sdk-1.0.0-20220812.061738-1.aar",
          "size": 4532959,
          "sha512": "a7ac216615c3cdde2dab1d163a94ab8d08a57803c9e843d62c13c415f7e5bd03afdedb58d6573db0d85591e0b369f42b7ad0ebdb754bb218cf81f8c9cf228782",
          "sha256": "2430924f2f28f36b9fcdaee4dc83e357bd9073bb008239749a79eff4c5ead6ec",
          "sha1": "2045b61b80ec5a2337265457b1b23c30b380e8d5",
          "md5": "72a84bde357e77cc3ff7db4afc9952c0"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.contrarywind",
          "module": "Android-PickerView",
          "version": {
            "requires": "4.1.6"
          }
        },
        {
          "group": "com.contrarywind",
          "module": "wheelview",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.1.54.android"
          }
        },
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "com.github.MingYueChunQiu",
          "module": "RecorderManager",
          "version": {
            "requires": "0.2.29"
          }
        },
        {
          "group": "com.github.PhilJay",
          "module": "MPAndroidChart",
          "version": {
            "requires": "v3.1.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.github.mcxtzhang",
          "module": "SwipeDelMenuLayout",
          "version": {
            "requires": "V1.3.0"
          }
        },
        {
          "group": "com.github.open-android",
          "module": "Logger",
          "version": {
            "requires": "v1.0.0"
          }
        },
        {
          "group": "com.google.android",
          "module": "flexbox",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.king.zxing",
          "module": "zxing-lite",
          "version": {
            "requires": "1.1.2-androidx"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.qiniu",
          "module": "qiniu-android-sdk",
          "version": {
            "requires": "8.4.2"
          }
        },
        {
          "group": "com.qcloud.cos",
          "module": "cos-android",
          "version": {
            "requires": "5.9.0"
          }
        },
        {
          "group": "com.shuyu",
          "module": "gsyVideoPlayer-java",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "com.shuyu",
          "module": "GSYVideoPlayer-exo2",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "com.shuyu",
          "module": "gsyVideoPlayer-ex_so",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "com.hyman",
          "module": "flowlayout-lib",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.github.alidili",
          "module": "FlowLayout",
          "version": {
            "requires": "v1.5"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.15"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle-android",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle-components",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle-kotlin",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.youth.banner",
          "module": "banner",
          "version": {
            "requires": "1.4.9"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.jetbrains.anko",
          "module": "anko",
          "version": {
            "requires": "0.10.8"
          },
          "excludes": [
            {
              "group": "com.google.android",
              "module": "android"
            }
          ]
        },
        {
          "group": "org.jetbrains.anko",
          "module": "anko-commons",
          "version": {
            "requires": "0.10.8"
          }
        },
        {
          "group": "androidx.gridlayout",
          "module": "gridlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk16",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "io.fotoapparat",
          "module": "fotoapparat",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "it.sephiroth.android.library.imagezoom",
          "module": "library",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv",
          "version": {
            "requires": "1.2.9"
          }
        }
      ],
      "files": [
        {
          "name": "hf-yjj-sdk-1.0.0-SNAPSHOT.aar",
          "url": "hf-yjj-sdk-1.0.0-20220812.061738-1.aar",
          "size": 4532959,
          "sha512": "a7ac216615c3cdde2dab1d163a94ab8d08a57803c9e843d62c13c415f7e5bd03afdedb58d6573db0d85591e0b369f42b7ad0ebdb754bb218cf81f8c9cf228782",
          "sha256": "2430924f2f28f36b9fcdaee4dc83e357bd9073bb008239749a79eff4c5ead6ec",
          "sha1": "2045b61b80ec5a2337265457b1b23c30b380e8d5",
          "md5": "72a84bde357e77cc3ff7db4afc9952c0"
        }
      ]
    }
  ]
}
